### ISSUE TITLE
rosrun ur5_vs gazebo_ibvs_two_features" in gazebo

### ISSUE THREAD

**Issue by harrycomeon** [deepakraina99/robot-vision-based-control#1]
Hi, Deepak Raina!  your job is outgoing! I want to ask a question . my question is the robot can not track a ball when i run the "rosrun ur5_vs gazebo_ibvs_two_features" in gazebo to Tracking using centroid of ball .  In detail , i can obtain the information
```
depth = nan
centroid (pixel) 0 0
centroid (image) -385.578 -216.888
Published Image data
```
when i run "rosrun object_detection camshift_only_tracker" .but when  i run the "rosrun ur5_vs gazebo_ibvs_two_features"  . the ur5 can not track the ball. In contrast, it move away the ball. in other direction, it still repeat the motion  all the time. it just like a hand swing from up to bottom . this is the output

![image](https://user-images.githubusercontent.com/28645542/82125418-6c10ec80-97d8-11ea-90cb-da7ca7add373.png)
maybe my description are not reasonale . I hope for your apply! thank you.

**Comment by harrycomeon** [comment]
the begin
![image](https://user-images.githubusercontent.com/28645542/82125570-6f58a800-97d9-11ea-90d1-c9f49ef8a62b.png)

when i run  "rosrun ur5_vs gazebo_ibvs_two_features" 
![image](https://user-images.githubusercontent.com/28645542/82125553-4e905280-97d9-11ea-94b4-a94e61eaa229.png)

I don't kown why the ur5 move to this place.

**Comment by deepakraina99** [comment]
Hi Harry,
The problem is with the blue ball coordinates in the image frame. 
Once the camera view window appears, select the blue ball (you want to track) using the mouse. For this, click anywhere on the window and drag it to the point so that ball is covered.

**Comment by harrycomeon** [comment]
Hi, Deepak Raina!  
You are right! It can work very well when i run "rosrun ur5_vs gazebo_ibvs_two_features" in gazebo. it can track the blue ball very well. But I have  another question when i run "rosrun ur5_vs gazebo_ibvs_three_features". It just like the gif when i run it.
![image](https://user-images.githubusercontent.com/28645542/82140167-4a5b4800-9860-11ea-8189-0e0cab834a95.png)

this is the output when I press enter to visual servoing.

![image](https://user-images.githubusercontent.com/28645542/82140192-7d054080-9860-11ea-9674-ab6290477cea.png)

I think it releate to the pid !  What do you think it? It s my honor to ask question to you.
I hope for your apply! Thank you!

**Comment by harrycomeon** [comment]
![1589705852686](https://user-images.githubusercontent.com/28645542/82140241-116fa300-9861-11ea-951b-1d1763245045.gif)

**Comment by harrycomeon** [comment]
Hi, Deepak Raina! I solve it by change the  desired distance to 0.55. Thank you! you are outgoing! I will closed the issue.

**Comment by deepakraina99** [comment]
This is due to the robot getting in singular position and controller returning infinite velocities in that configuration. Please keep the target inside the workspace of the robot. This can be changed using the world files available in src/universal_robot/ur_gazebo/worlds/{world_type}.world. Please read about URDF terminology for understanding this file.

**Comment by harrycomeon** [comment]
Thank you, It can help me a lot !



At 2020-05-17 18:09:59, "Deepak Raina" <notifications@github.com> wrote:

This is due to the robot getting in singular position and controller returning infinite velocities in that configuration. Please keep the target inside the workspace of the robot. This can be changed using the world files available in src/universal_robot/ur_gazebo/worlds/{world_type}.world. Please read about URDF terminology for understanding this file.

**Comment by harrycomeon** [comment]
Thanks a lot ! I will think about the project again !



At 2020-05-17 15:52:19, "Deepak Raina" <notifications@github.com> wrote:

Hi Harry,
The problem is with the blue ball coordinates in the image frame.
Once the camera view window appears, select the blue ball (you want to track) using the mouse. For this, click anywhere on the window and drag it to the point so that ball is covered.
