### ISSUE TITLE
Joint Velocity limit exceeded After rosrun ur5_vs new_ibvs_two_features

### ISSUE THREAD

**Issue by harrycomeon** [deepakraina99/robot-vision-based-control#2]
Hi，Deepak Raina!
Not long ago, I have asked you some question about IBVS in gazebo.
which is about the project , https://github.com/deepakraina99/robot-vision-based-control

Now, I get back to school, I am doing the project in real UR5. I achieved the hand eye calibration，what's more， I can use the object_detection to track the red object . 

![image](https://user-images.githubusercontent.com/28645542/88444017-9cff4480-ce4d-11ea-8bd8-80265936da44.png)

**But I have some difficulty in Tracking using centroid of ball after
rosrun ur5_vs new_ibvs_two_features**

**This is the question when I run it, then come to the initial pose . when I launch visual servo , It will have the tip that Joint Velocity limit exceeded!**

![image](https://user-images.githubusercontent.com/28645542/88444056-c4561180-ce4d-11ea-8596-a6cb7100c1e2.png)

I look through the code ,i find double vel_limit = 3.0; //i.e. 3 radian/sec

![image](https://user-images.githubusercontent.com/28645542/88444064-d2a42d80-ce4d-11ea-9ec7-e3d0dd00b2ea.png)

The main problem is why the velocity is so big ?
In fact ,I dont know how to add the convert between the ee_link and camera_link .I find you change the ur5_robot.urdf.xacro IN ~/catkin_ws/src/universal_robot/ur_description/urdf,

![image](https://user-images.githubusercontent.com/28645542/88444076-e18ae000-ce4d-11ea-8f2d-11066d7a6890.png)

Then you have the convert in my_funcs.h . (~ /catkin_ws/src/ur5_vs/include)

![image](https://user-images.githubusercontent.com/28645542/88444093-f1a2bf80-ce4d-11ea-94c8-6b9db4626447.png)

I don't know how to do it . can you give me some advices . Thank you ! I look forward to have your reply！

**Comment by harrycomeon** [comment]
Hi，Deepak Raina!

Today, I repeatly  do a hand eye calibarition .

I add the result the ur5_robot.urdf.xacro by the under way.

`  <link name="camera_link" />

  <joint name="camera_link_joint" type="fixed">
    <parent link="ee_link" />
    <child link = "camera_link" />
    <origin xyz="0.0173819897999 0.0032833323036 0.117884899185" xyzw=" -0.532388013231 0.492905079405  -0.476385852942 0.496652902117" />
  </joint>`

What'more, when i launch the roslaunch ur_modern_driver ur5_bringup.launch robot_ip:=192.168.1.107 .

after that I open the rviz ,I find tf tree , it fit the real scene .
![image](https://user-images.githubusercontent.com/28645542/88446601-08511280-ce5e-11ea-8ade-7e8c38128c0e.png)

 But when I run rosrun ur5_vs new_ibvs_two_features. it always products the error. that is **[ERROR] [1595642112.308599540]: Joint Velocity limit exceeded !**

This is the second data.
![image](https://user-images.githubusercontent.com/28645542/88446651-6bdb4000-ce5e-11ea-8b80-c9c1bb97f6a9.png)
![image](https://user-images.githubusercontent.com/28645542/88446665-84e3f100-ce5e-11ea-8523-762ead66cd26.png)

Can you give me some advices about the velocity is so big ? Thank you , I am looking forward to your reply !

**Comment by harrycomeon** [comment]
![1](https://user-images.githubusercontent.com/28645542/88447661-4c491500-ce68-11ea-9776-a6a86ad2764c.gif)
Which is the terminal and camera demo.

**Comment by deepakraina99** [comment]
For hand-eye calibration, you need to follow the procedure. Its like noting down xyz corrdinates of at least 12 world points from both camera and end-effector frame, and then find the transformation using any linear algebra technique for solving Ax=B. I think you have found the transformation matrix manually, that can be also be done, but in case the camera-frame is oriented in a different manner, then this will not work.

If you have calibrated the camera correctly, you need to include that transformation in _new_ibvs_two_features.cpp_ file. As I am seeing in the terminal window, both velocities in ee_frame and camera_frame are same. They should be different in your case, since both frames are not same.

**Comment by harrycomeon** [comment]
Thanks a lot，I have calibrated the camera ，but indeed  both ”velocities in ee_frame and camera_frame are same “ is a problem . I will try agian ,maybe I don't deal with the transformation between camera and ee_link.

**Comment by harrycomeon** [comment]
Hi，Deepak Raina!

Today, I repeatly do a hand eye calibarition . Then change the relavant code. what's more , i increase the value of velocity limit to 8.
But the ur5 moves to opposite direction . it leads the mean error increasing . Can you give me some advice about this question.

this is the show。

![1](https://user-images.githubusercontent.com/28645542/88471394-86cfb200-cf3b-11ea-90b1-6c8167cc265e.gif)


Thanks.

**Comment by deepakraina99** [comment]
Check by giving direct velocity commands in task space to robot. You can write a simple code for this or can also edit in _new_ibvs_two_features.cpp_ using the following code at the appropriate location
````
// 6d velocity vector [Vx, Vy, Vz, omega_x, omega_y, omega_z]
Vb = [0.1; 0.0; 0.0; 0.0; 0.0; 0.0]; 
theta_dot = Jg_inv * Vb; 
````
Check robot motion by giving different velocities whether it's moving in correct direction or not.

**Comment by harrycomeon** [comment]
OK, I will try it, Thanks.

**Comment by harrycomeon** [comment]
Hi,Deepak Raina!

I try to send different 6d velocity vector through your tip，I find my ur5 will shake all time ，what'more，the Joint velocity will change although the vb is not change. whether my base is not stable .

this is the code and terminal.
 ```
// 6d velocity vector [Vx, Vy, Vz, omega_x, omega_y, omega_z]
        Vb.at<double>(0,0)=0.0;
        Vb.at<double>(1,0)=0.0;
        Vb.at<double>(2,0)=0.001;
        Vb.at<double>(3,0)=0.0;
        Vb.at<double>(4,0)=0.0;
        Vb.at<double>(5,0)=0.0;
```
![image](https://user-images.githubusercontent.com/28645542/88474491-7b8b7f00-cf59-11ea-9bde-e5ebeed6b7fb.png)
![image](https://user-images.githubusercontent.com/28645542/88474497-834b2380-cf59-11ea-9e01-3ee2e2a29caf.png)
in different time, the Joint velocity  will change .

**Comment by deepakraina99** [comment]
The joint velocity will change. The mapping between end-effector velocity and joint velocity is given by Jacobian, which is a function of joint angles. Since joint angles are changing, thus joint velocity will change accordingly. 
Further, the shaky motion fo robot is observed when your loop time (time for publishing joint velocities) is quite high. Please check.
Is your robot moving along the appropriate direction with direct velocity control?

**Comment by harrycomeon** [comment]
Thanks，Deepak Raina!
 i understand why the  joint velocity is always change accordingly.  Beacuse of the RobotJacobian is relavant to the joint_states . and the shaky motion maybe relavant to the loop time. It is 0.01 ,i will change it to do some trials.     
```
double total_time = ros::Time::now().toSec();
    ros::Rate rate(100);
```
**I don't know the velocity direaction is correspendence to the base coordinate . for example, Vx=0.1,  Vy=0, Vz=0, omega_x=0, omega_y=0, omega_z=0,and  whether the UR5 eelink will move down the x of base coordinate .**

**Another question is the  under code ,why the  data is**     
    dce.at<double>(0,0)=-0.00277013;
    dce.at<double>(1,0)=0.0131105;
    dce.at<double>(2,0)=0.06704;

**It is relavant to what ?**
```
void newconvertVelCameratoEEframe(cv::Mat Vc,cv::Mat Ve)
{

    Mat dce = Mat(3, 1, CV_64F, 0.0);
    dce.at<double>(0,0)=-0.00277013;
    dce.at<double>(1,0)=0.0131105;
    dce.at<double>(2,0)=0.06704;

//    dce.at<double>(0,0)=0.0248363734103;
//    dce.at<double>(1,0)=0.0433781224343;
//    dce.at<double>(2,0)=0.137763058005;

    //cout << "dce " << dce << endl;

    Mat Rot = Mat::eye(3,3,CV_64F);

    //Skew-symmetric matrix of dce vector
    cv::Mat S_dce = cv::Mat(3, 3, CV_64F, 0.0);
    S_dce.at<double>(0,1) =  -dce.at<double>(2,0);
    S_dce.at<double>(0,2) =   dce.at<double>(1,0);
    S_dce.at<double>(1,0) =   dce.at<double>(2,0);
    S_dce.at<double>(1,2) =  -dce.at<double>(0,0);
    S_dce.at<double>(2,0) =  -dce.at<double>(1,0);
    S_dce.at<double>(2,1) =   dce.at<double>(0,0);
    //cout << "S_ce " << S_ce << endl;

    //transformation 2nd term
    cv::Mat trans_2ndterm = cv::Mat(3, 3, CV_64F, 0.0);
    trans_2ndterm = S_dce*Rot;
    //cout << "trans2ndterm " << trans_2ndterm << endl;

    //transformation to convert camera velocity to ee-velocity
    cv::Mat trans = cv::Mat(6, 6, CV_64F, 0.0);

    Rot.copyTo(trans(Rect(0,0,Rot.cols,Rot.rows)));
    trans_2ndterm.copyTo(trans(Rect(3,0,trans_2ndterm.cols,trans_2ndterm.rows)));
    Rot.copyTo(trans(Rect(3,3,Rot.cols,Rot.rows)));
    //cout << "trans " << trans << endl;

    Ve = trans*Vc; //end-effector velocity
}
```
Thanks a lot , you give me a lot help.

**Comment by deepakraina99** [comment]
To understand the function _newconvertVelCameratoEEframe_, I would suggest you to read section 12.5 of this book: Robot Modeling and Control by Mark W. Spong, Seth Hutchinson, M. Vidyasagar. In fact, you should read the whole Chapter 12: Vision-based control of this book.

**Comment by harrycomeon** [comment]
Ok , thank you , i will read the Chapter . indeed i don't understand the principle.

**Comment by harrycomeon** [comment]
Hi, Doctor Deepak Raina!

I have read the book and your paper, I roughly understand the relationship between camera and ee_link , so I repeatedly do a calibration and modify the code of my_funs.h. What's more, I decrease the frequency of the velocity's publication. It can relieve the shake.

Now, I can control the UR5 according to the red ball. But it seems to not do a visual servo. The mean_error is not reducing all the time. can you give me some tips about this question? On account of the video is so big, I will send it to your Linkedin.   Thanks a lot, I look forward to your reply!

**Comment by deepakraina99** [comment]
Please share the video, then I will be able to suggest.
Is your direct end-effectory velocity control working fine?

**Comment by harrycomeon** [comment]
Okay,  because the Github limit the video capacity range in 10 M. So  I will Split it. 

When I direct end-effectory velocity control, It does not work fine.

in this case, it can work fine
![image](https://user-images.githubusercontent.com/28645542/88627986-cafbb780-d0df-11ea-9858-631df2640468.png)
But in other cases, it does not work very well.
just like
![image](https://user-images.githubusercontent.com/28645542/88628071-ed8dd080-d0df-11ea-8e40-dc380d944793.png)
![image](https://user-images.githubusercontent.com/28645542/88628081-f54d7500-d0df-11ea-993e-60b303d95a5e.png)
Why is it? can you give me some tips? Thanks.

**Comment by deepakraina99** [comment]
Try using the function _getRobotJacobian_ in place of _newgetRobotJacobian_ in the following section of code.

````//Obtaining robot Jacobian
        double th[6]={jp1, jp2, jp3, jp4, jp5, jp6};
        //cout << "current joint angles " << jp1 << " " << jp2 << " " << jp3 << " " << jp4 << " " << jp5 << " " << jp6 << endl;
        newgetRobotJacobian(th,Jg);
`````

**Comment by harrycomeon** [comment]
Perfect，It can work very well. I will try it again.

**Comment by harrycomeon** [comment]
Hi, Doctor Deepak Raina!

Now, I can control the UR5 through direct end-effectory velocity control. But when I use the camera velocity and convert to the ee_link and base_link. It's not doing a correct visual servo according to except.can you give me some tips. Thanks. 

This is currently a tracking result. But the mean error is not continually decreased.

![1](https://user-images.githubusercontent.com/28645542/88653495-bed32280-d0fe-11ea-98e0-db0804fd8b6e.gif)

**Comment by deepakraina99** [comment]
Check feature values. Are they correct? They should be zero when the object is in the center of image.
Another thing you should try is mounting the camera exactly at the center of the robot end-effector and then check 2D visual servoing. It will help us in identifying if there is any calibration error.

**Comment by harrycomeon** [comment]
Ok, Thanks, I will try it. You give me a lot of help. Thanks again.

**Comment by harrycomeon** [comment]
I have another small question about camera_link.
I use the real sense D435i, It has many camera joints and links. 
This is the link pose, I need to choose a link representing a camera_link. Can you tell me I should choose which, or either of them is ok?

camera_color_optical_frame

![image](https://user-images.githubusercontent.com/28645542/88743657-c682dd80-d177-11ea-902d-bfe5d7488422.png)

camera_link

![image](https://user-images.githubusercontent.com/28645542/88743720-f16d3180-d177-11ea-964b-1b95590c0d04.png)

**Comment by deepakraina99** [comment]
You need to choose the frame corresponding to the camera taking the RGB image. I think it should be camera link.

**Comment by harrycomeon** [comment]
OK, Thanks. I will try it again.

**Comment by harrycomeon** [comment]
Hi, Doctor Deepak Raina!

Tonight, I can do a slow visual servo. But it is slower than your video. It needs a longer time to track the red ball. can you give me some tips about it! 
this is the code
```
    ros::Rate rate(100);
    while(ros::ok())
```
 I change the rate to bigger. I find it can wander around the visual servo point. Do you have other ways to make UR5 more Supple?

Another question is the difference of newgetRobotJacobian and getRobotJacobian.I find it is so different in the formula.

Thanks a lot! I look forward to your reply!

**Comment by deepakraina99** [comment]
The rate of 100 is perfect. As I mentioned earlier, I found the reason for slow speed is time consumption in a while loop. Please check in your loop where it is consuming more time. Try to remove all cout (print) statements. They also consume a lot of time. Just check and let me know.

**Comment by harrycomeon** [comment]
Yeah, I remove all cout (print) statements. It can move faster, but it has a stronger shake of UR5. can you give me some tips? Thanks.
This is the limit of velocity and accel.
```
        double vel_limit = 3.0; //i.e. 3 radian/sec
//        double acc_limit[6] = {5.0,4.0,4.0,4.0,3.0,5.0}; //i.e. 4 radian/sec^2

        double acc_limit[6] = {5.0,4.0,4.0,4.0,3.0,2.0}; //i.e. 4 radian/sec^2
```

**Comment by deepakraina99** [comment]
Is this shaky behavior only observed during visual servoing? Or also during the direct end-effector velocity control?

**Comment by harrycomeon** [comment]
Both of them, they have a stronger shake of UR5.

**Comment by deepakraina99** [comment]
Then there must be an issue with ur_moden_driver. Download the appropriate version of it from https://github.com/ros-industrial/ur_modern_driver.

**Comment by harrycomeon** [comment]
Thanks a lot, I will try it later.

**Comment by harrycomeon** [comment]
I change the pack of ur_modern_driver. The problem is still being. 

Universal_Robots_ROS_Driver needs the For using the ur_robot_driver with a real robot you need to install the external control-1.0.2.urcap which can be found inside the resources folder of this driver.  So I don't try it.

I want to ask whether maybe the getRobotJacobian(th,Jg) problem.

**Comment by harrycomeon** [comment]
If you are convenient, can you share with me your ur_modern_driver?  Of course, it may be not working.

**Comment by harrycomeon** [comment]
Thanks, I cry. I succeed when I change the rate to 200. It can work well. Thanks,  Doctor Deepak Raina! You give me very very much help. I will help others just like you. You are my model. I will close the question. Maybe I will ask you other question about it. Thanks again!

**Comment by deepakraina99** [comment]
> Thanks, I cry. I succeed when I change the rate to 200. It can work well. Thanks, Doctor Deepak Raina! You give me very very much help. I will help others just like you. You are my model. I will close the question. Maybe I will ask you other question about it. Thanks again!

Dear @harrycomeon,
Thanks for the kind words. I am happy that it worked for you. Feel free to ask me any queries in the future as well. Please share a nice visual servoing video with me on my Gmail - deepakraina99@gmail.com.
Best wishes.

**Comment by deepakraina99** [comment]
> Thanks, I cry. I succeed when I change the rate to 200. It can work well. Thanks, Doctor Deepak Raina! You give me very very much help. I will help others just like you. You are my model. I will close the question. Maybe I will ask you other question about it. Thanks again!

Dear @harrycomeon,
Thanks for the kind words. I am happy that it worked for you. Feel free to ask me any queries in the future as well. Please share a nice visual servoing video with me on my Gmail - deepakraina99@gmail.com.
Best wishes.
