### ISSUE TITLE
rosrun ur5_vs new_ibvs_three_features

### ISSUE THREAD

**Issue by harrycomeon** [deepakraina99/robot-vision-based-control#3]
HI, Doctor Deepak Raina!

When I run "rosrun ur5_vs new_ibvs_three_features", The UR5 can track the ball of x,y. But It can not track z-axis. I test it can move when I use the direct velocity in the z-axis. Can you give me some advice about it?
![image](https://user-images.githubusercontent.com/28645542/89010957-275e1180-d342-11ea-9b41-9d9a1be39046.png)
![image](https://user-images.githubusercontent.com/28645542/89011144-7c9a2300-d342-11ea-9b3b-dbda747e4249.png)

Another question is there are mean error is not 0. What about it? Except hand-eye calibration can affect it, are there other factors can affect it? I try to modify the hand-eye result, But it has a little effect on the mean error.

**Comment by deepakraina99** [comment]
Since the error in the Z direction is quite less in comparison to XY, so velocity generated along z-direction is quite less. You can try using different proportional gain (Kp) values for z-direction. Increase the value gradually and check.
I could not understand your second question. Mean error will not be zero initially, right?

**Comment by deepakraina99** [comment]
Regarding the second question, I think you must have changed this part of code. Please check
```
 if (sqrt_mean_error == 0)
            break;
```

**Comment by harrycomeon** [comment]
Ok, I will try it.

**Comment by deepakraina99** [comment]
Show me the camera velocity (Vc) and end-effector velocity (Ve) and velocity in base frame (Vb) components.

```
        //Convert velocity from camera frame to end-effector frame
        newconvertVelCameratoEEframe(Vc,Ve);
        //duration = ros::Time::now().toSec() - total_time;
        //cout << "-------------------------t2="<<duration<<"---------------------" << endl;
        //cout << "Velocity: eelink_frame  " << Ve << endl;

        //Convert velocity from end-effector frame to base frame
        newConvertVelEEtoBaseframe(Vc,Vb);
        //duration = ros::Time::now().toSec() - total_time;
        //cout << "-------------------------t3="<<duration<<"---------------------" << endl;
        //cout << "Velocity: base_frame " << Vb << endl;
```
have you corrected the above code for your case? It should be 
```
newConvertVelEEtoBaseframe(Ve,Vb);

```

**Comment by harrycomeon** [comment]
Yeah, I have correct it in mine code.
```
//Way-2
        computeImageJacobian(m,depth_p,L);
        cv::invert(L, Linv, cv::DECOMP_SVD);
        Vc = -Linv * Error_PID;


        //Convert velocity from camera frame to end-effector frame
        newconvertVelCameratoEEframe(Vc,Ve);
        //duration = ros::Time::now().toSec() - total_time;
        //cout << "-------------------------t2="<<duration<<"---------------------" << endl;
        //cout << "Velocity: eelink_frame  " << Ve << endl;

        //Convert velocity from end-effector frame to base frame
        newConvertVelEEtoBaseframe(Ve,Vb);
        //duration = ros::Time::now().toSec() - total_time;
        //cout << "-------------------------t3="<<duration<<"---------------------" << endl;
        //cout << "Velocity: base_frame " << Vb << endl;
```

**Comment by harrycomeon** [comment]
This is in the terminal.
![image](https://user-images.githubusercontent.com/28645542/89092173-051bd080-d3e2-11ea-8c10-b5d6edc3450b.png)

![image](https://user-images.githubusercontent.com/28645542/89092167-f59c8780-d3e1-11ea-9272-09211f1ac2a7.png)

**Comment by harrycomeon** [comment]
Dear Mr. Deepak
I don't  understand why is depth_p[0]=0.7, depth_p[1]=0.7?
in this code,
```
double depth_p[2]={0,0}, prev_depth[2]; //depth of centroid
    //depth_p[0]=(double)centroid_depth, depth_p[1]=(double)centroid_depth;
    depth_p[0]=0.7, depth_p[1]=0.7;
    prev_depth[0]=depth_p[0], prev_depth[1]=depth_p[1];

    double m[3]={0,0,0};
    m[0]= (u_c[0]-320)/(606.0125732421875/640);    //(u-u0)/px
    m[1]= (u_c[1]-240)/(606.0125732421875/480);    //(v-v0)/py
    m[2]= centroid_depth;
```

**Comment by deepakraina99** [comment]
Is the robot not at all moving in z-direction ? or moving slowly ? Try just moving in depth. Keep current feature as [0, 0, val(current_depth)] and desired feature as [0, 0, val(desired_depth)].

depth_p has been kept 0.7 as desired. The camera that I was using has some limits for point cloud data say 0.5 to 1.2 distance units. If you go beyond these limits, depth information will not be available. Check with your camera by manually moving the robot to and fro from the object and check up to what limits it gives you depth information.

**Comment by harrycomeon** [comment]
OK, I will try it again.

**Comment by harrycomeon** [comment]
It is the robot not at all moving in the z-direction.
I try to keep the error_x and error_y close to 0, but when I move the object in z. The error_z is not changed too much in the picture.
This is the error_z.
![image](https://user-images.githubusercontent.com/28645542/89101118-bbf26d80-d42f-11ea-9d3f-202b05342ca3.png)

I find the depth will change when I move the object. I can see it by observing the terminal.
![image](https://user-images.githubusercontent.com/28645542/89101159-f2c88380-d42f-11ea-822f-66dfc738e71b.png)

**Comment by harrycomeon** [comment]
Dear Mr. Deepak

This is my new_ibvs_three_features.cpp in my ur5_vs.

Deepak Raina <notifications@github.com> 于2020年8月1日周六 下午4:51写道：

**Comment by harrycomeon** [comment]
Dear Mr. Deepak

I search that my camera working distance is 0.1-10m. What's more, when I move the object in the z-axis. It can see the distance changing in the terminal.

**Comment by deepakraina99** [comment]
Try changing the gain parameter (Kp) for depth.

**Comment by harrycomeon** [comment]
Ok, I will try it again.

**Comment by harrycomeon** [comment]
Thanks, again! I find the Error_PID.at<double>(2,0)=0 when I convert the velocity from vc to ve, so I change the Error_PID.at<double>(2,0) of ve, at the same time, I change the p of z, Now, I can control the robot in z.
