### ISSUE TITLE
rosrun object_detection camshift_kalman_tracker

### ISSUE THREAD

**Issue by harrycomeon** [deepakraina99/robot-vision-based-control#4]
Hi, Mr. Deepak Raina!
When I rosrun object_detection camshift_kalman_tracker, I find there is only one Box in the image. Can you tell me why?
![image](https://user-images.githubusercontent.com/28645542/89414532-20c60480-d75d-11ea-96d5-dcddef944d8d.png)

This is in your video.
![image](https://user-images.githubusercontent.com/28645542/89413116-d17ed480-d75a-11ea-86ee-c21c56cd21ee.png)

I want to understand the cam shift + Kalman in the short-lived blocking. can you give me some advice?

**Comment by deepakraina99** [comment]
Try using camshift_kf_tracking. Some parts of the code must have been commented in camshift_kalman_tracking to display the second rectangle.

**Comment by harrycomeon** [comment]
Ok, I will try it again.

**Comment by harrycomeon** [comment]
when I use camshift_kf_tracking, it still has no second rectangle. can you give me some advice about it? I don't know how to correct the code about camshift_kalman_tracking.

**Comment by deepakraina99** [comment]
Please read the following link to understand this code: https://www.myzhar.com/blog/tutorials/tutorial-opencv-ball-tracker-using-kalman-filter/
It would be good to read some basics about Kalman filter.

**Comment by harrycomeon** [comment]
Thanks,again！ Your reference give me big help！ I will read it patiently.

**Comment by deepakraina99** [comment]
Dear @harrycomeon, I hope the issue has been resolved now. Feel free to ask any queries.

**Comment by harrycomeon** [comment]
Thanks,again.It can help me a lot.
